services:
  - type: web
    name: cortexa-ai
    env: python
    rootDir: ai
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
